### ISSUE TITLE
Count aggregation form

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/prezento#142]
Add it to the aggregation form combo for MetricConfiguration creation.

Depends on

* https://github.com/mezuro/kalibro_processor/issues/54
* https://github.com/mezuro/kalibro_processor/issues/55

Don't forget about generation a pull request to the `dev` branch.

**Comment by ParleyMartins** [comment]
UnB Team will do this.

**Comment by rafamanzo** [comment]
Have a look at this message with discussions regarding this issue: http://librelist.com/browser//mezuro/2015/3/24/unb-team-progress/#554ae2e88b60502de9115e54a7148e20

**Comment by rafamanzo** [comment]
Now we expect PR on ```master``` sorry for the misleading description.

**Comment by marcheing** [comment]
Closed by #194
