### ISSUE TITLE
Bug on metric result's graphic

### ISSUE THREAD

**Issue by diegoamc** [mezuro/prezento#222]
Click on the _pain_ metric on [this repoitory](http://mezuro.org/en/projects/60/repositories/102) to see the bug 

For a better debug process, would be nice to create javascript unit tests, using [Konacha] (https://github.com/jfirebaugh/konacha).

**Comment by rafamanzo** [comment]
This one is worse: http://mezuro.org/en/projects/60/repositories/103

**Comment by rafamanzo** [comment]
Closed by: https://github.com/mezuro/prezento/pull/226
