### ISSUE TITLE
Unknown format error handling

### ISSUE THREAD

**Issue by diegoamc** [mezuro/prezento#223]
When a user makes a request with using formats we do not support (txt, for example), rails throws an exception.
We would like to catch those exceptions and render a standard error page for that error.

We already do that when the record is not found. See the [404 error page](https://github.com/mezuro/prezento/blob/907442b6e8dccd48830446c60a93ec91133b7be8/public/404.html), an example of when we [throw the exception](https://github.com/mezuro/prezento/blob/ba131e659e2c2e10daf79f7be755a64c7da99ffe/app/models/kalibro_configuration.rb) and how we [catch it](https://github.com/mezuro/prezento/blob/8842352bc59e6d4e0347d01f6b948e07401e7313/app/controllers/application_controller.rb) for more details.

**Comment by rafamanzo** [comment]
PR: https://github.com/mezuro/prezento/pull/224

This is actually a bug introduced by https://github.com/mezuro/prezento/pull/205

**Comment by danielkza** [comment]
PR was already accepted, closing.
