### ISSUE TITLE
Multiple Attributes for the same resource

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/prezento#244]
All the attributes do not validate that the Resource (like KalibroCofiguration, Repository or ReadingGroup) id unique.

We need to add that validation.

**Comment by diegoamc** [comment]
We should create a validation of `repository_id` scoped to the `user_id`, for example.
Check out [this](http://edgeguides.rubyonrails.org/active_record_validations.html#uniqueness) reference.

ProjectAttributes should have this kind of validation too.

**Comment by vitorbaraujo** [comment]
Those validations where already added?

**Comment by paulormm** [comment]
@rafamanzo and @athos-ribeiro about that?

**Comment by rafamanzo** [comment]
Closed via https://github.com/mezuro/prezento/pull/386
