### ISSUE TITLE
Handle unsupported format requests

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/prezento#301]
As of https://lists.ime.usp.br/archives/mezuro-core/2016-January/006557.html it is possible that requests ask for unsupported formats like JPEG.

We should handle `ActionView::MissingTemplate` check if the error was really caused by unsupported format and respond accordingly with HTTP 406 `head(:not_acceptable)`.

**Comment by danielkza** [comment]
This seems like a duplicate of #296, just maybe a bit more generic. Is that the case?

**Comment by rafamanzo** [comment]
They overlap. I suggest to migrate #296 text to this one.
