### ISSUE TITLE
Remove RepositoryAttributes when destroying a Repository

### ISSUE THREAD

**Issue by diegoamc** [mezuro/prezento#347]
Currently, we are leaving repository attributes on the database when we destroy a repository.

The correct behaviour should be to remove the attributes before destroying the repository. Take a look at how we do it for [Projects](https://github.com/mezuro/prezento/blob/master/app/models/project.rb#L30).

**Comment by wiltonsr** [comment]
How can i reproduce this bug?
I tried reproduce de behavior in my machine, but the repository attributes were deleted.

**Comment by rafamanzo** [comment]
Hi @wiltonsr ,

Can you post the code you are using to replicate?

**Comment by wiltonsr** [comment]
I made the test using the code that is in master branch, currently. After this I browsed the data in the console and it was correctly deleted.

**Comment by rafamanzo** [comment]
Within `rails console` trye the following:

```ruby
RepositoryAttributes.count
r = Repository.create(name: 'a', address: 'a', kalibro_configuration_id: 1)
RepositoryAttributes.create(repository: r, user_id: 1)
RepositoryAttributes.count
r.destroy
RepositoryAttributes.count
```
(notice this is not a good unit test as it relies on writing to the database)

You should see the `RepositoryAttributes` instance is still there.
