### ISSUE TITLE
Move "public" funcionality to a module

### ISSUE THREAD

**Issue by diegoamc** [mezuro/prezento#349]
If you look the [Project](https://github.com/mezuro/prezento/blob/master/app/models/project.rb), [Repository](https://github.com/mezuro/prezento/blob/master/app/models/repository.rb), [ReadingGroup](https://github.com/mezuro/prezento/blob/master/app/models/reading_group.rb) and [KalibroConfiguration](https://github.com/mezuro/prezento/blob/master/app/models/kalibro_configuration.rb) models, you'll see they are quite similar.

That similarity comes from Prezento's feature of hiding those entities, if desired. All the code regarding this funcionality could be moved to a module. That would avoid much duplication and would standardize our business logic.

**Comment by wiltonsr** [comment]
This merge #382 is enough to change this issue to done?

**Comment by rafamanzo** [comment]
Yes indeed. Thank you! :champagne:
